# name: Fraud Detection MLOps Pipeline

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build-docker:
#     uses: ./.github/workflows/image.yml
#     secrets: inherit

#   deploy-terraform:
#     uses: ./.github/workflows/infra.yml
#     needs: build-docker
#     secrets: inherit